
[project]
authors = [
    "Durrant Lab <durrantj@pitt.edu>",
]
channels = ["conda-forge"]
name = "wispy"
description = "Trajectory analysis tool that calculates and visualizes allosteric pathways."
platforms = ["win-64", "linux-64", "osx-64"]
version = "0.0.0"
license = "Apache-2.0"
readme = "README.md"

[pypi-dependencies]
wispy = { path = ".", editable = true }

[system-requirements]
linux = "3.10.0"
libc = { family="glibc", version="2.17" }

[environments]
dev = ["dev"]
docs = ["docs"]

[tasks]

[dependencies]
python = ">=3.9,<3.13"
loguru = ">=0.7.2,<0.8"
networkx = ">=3.4.2,<4"
numpy = ">=2.2.2,<3"
scipy = ">=1.15.1,<2"
pyyaml = ">=6.0.2,<7"

[feature.dev.dependencies]
black = ">=23.10.0"
isort = ">=5.12.0"
pylint = ">=3.0.1"
mypy = ">=1.6.0"
pytest = ">=7.4.2"
pytest-cov = ">=4.1.0"
coverage = ">=7.3.1"
pytest-html = ">=4.0.1"
colorama = ">=0.4.6"

[feature.dev.tasks]
mdlint = { cmd = ["markdownlint-cli2", '"**/*.{md,markdown}"', "--fix", "--config", ".markdownlint.yaml", "||", "true"] }
isort = { cmd = ["isort", "--settings-path", ".isort.cfg", "./wisp", "./tests", "||", "true"] }
black = { cmd = ["black", "--config", ".black.toml", "./wisp", "./tests", "||", "true"] }
format = { depends-on = ["mdlint", "isort", "black"] }
tests = { cmd = [
    "PYTHONPATH=.",
    "pytest",
    "-c",
    ".pytest.ini",
    "--cov='wisp'",
    "--cov-report=xml",
    "--junit-xml=report.xml",
    "--failed-first",
]}
coverage = { cmd = ["coverage", "report"] }
cleanup-build = { cmd = ["rm", "-rf", "./build"] }
build = { cmd = ["python3", "-m", "build"], depends-on = ["cleanup-build"]}
publish-test = { cmd = ["twine", "upload", "--repository", "testpypi", "dist/*"] }
publish = { cmd = ["twine", "upload", "dist/*"] }

[feature.dev.pypi-dependencies]
build = ">=1.2.2.post1,<2"
mypy-extensions = ">=1.0.0"

[feature.docs.dependencies]
mkdocs = ">=1.6.1,<2"
mkdocs-material = ">=9.5.44,<10"
pymdown-extensions = ">=10.12,<11"
mkdocs-table-reader-plugin = ">=3.1.0,<4"
mkdocstrings = ">=0.26.2,<0.27"
mkdocstrings-python = ">=1.12.2,<2"
mkdocs-gen-files = ">=0.4.0,<0.5"
mkdocs-macros-plugin = ">=1.3.7,<2"
mkdocs-jupyter = ">=0.25.0,<0.26"
mkdocs-glightbox = ">=0.4.0,<0.5"
mkdocs-git-revision-date-localized-plugin = ">=1.2.9,<2"

[feature.docs.pypi-dependencies]
material-plausible-plugin = ">=0.2.0,<0.3"
mkdocs-awesome-pages-plugin = ">=2.9.3,<3"
mkdocs-print-site-plugin = ">=2.6.0,<3"

[feature.docs.tasks]
docs = { cmd = ["rm", "-rf", "./public/", "&&", "mkdocs", "build", "-d", "public/"] }
serve = { cmd = ["mkdocs", "serve"] }
