[tool.poetry]
name = "wisp"
version = "1.4.0"
description = ""
authors = [
    "Durrant Lab",
]
readme = "README.md"
license = "AFL-3.0 "

[tool.poetry.scripts]
wisp = "wisp.run:main"

[tool.poetry.dependencies]
python = "<3.13,>=3.9"
networkx = "^3.2"
scipy = "^1.11.3"
loguru = "^0.7.2"

[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
black = "^23.10.0"
pyupgrade = "^3.15.0"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.2"
pytest-cov = "^4.1.0"

[tool.pylint.messages_control]
good-names = [
    "i",
    "j",
    "k",
    "e",
    "_",
]
ignore = [
    "CVS",
    "_version.py",
    "conf.py",
]
jobs = 0
py-version = 3.11
argument-naming-style = "snake_case"
attr-naming-style = "snake_case"
class-const-naming-style = "UPPER_CASE"
class-naming-style = "PascalCase"
const-naming-style = "UPPER_CASE"
function-naming-style = "snake_case"
disable = [
    "raw-checker-failed",
    "bad-inline-option",
    "locally-disabled",
    "file-ignored",
    "suppressed-message",
    "useless-suppression",
    "deprecated-pragma",
    "use-symbolic-message-instead",
    "too-many-arguments",
    "too-many-public-methods",
    "missing-module-docstring",
    "missing-function-docstring",
    "too-many-lines",
    "fixme",
    "too-many-instance-attributes",
    "too-few-public-methods",
    "too-many-locals",
    "attribute-defined-outside-init",
    "broad-except",
    "import-error",
]

[tool.black]
target-version = [
    "py311",
]
line-length = 88
color = true
exclude = "/(\n    \\.git\n    | \\.hg\n    | \\.mypy_cache\n    | \\.tox\n    | \\.venv\n    | _build\n    | buck-out\n    | build\n    | dist\n    | env\n    | venv\n)/\n"

[tool.isort]
py_version = 311
line_length = 88
known_typing = [
    "typing",
    "types",
    "typing_extensions",
    "mypy",
    "mypy_extensions",
]
sections = [
    "FUTURE",
    "TYPING",
    "STDLIB",
    "THIRDPARTY",
    "FIRSTPARTY",
    "LOCALFOLDER",
]
profile = "black"
include_trailing_comma = true
multi_line_output = 3
indent = 4
color_output = true
skip = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

[tool.mypy]
python_version = 3.11
pretty = true
show_traceback = true
color_output = true
allow_redefinition = false
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
ignore_missing_imports = true
implicit_reexport = false
no_implicit_optional = true
show_column_numbers = true
show_error_codes = true
show_error_context = true
strict_equality = true
strict_optional = true
warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.pytest.ini_options]
norecursedirs = [
    "reptar",
    "hooks",
    "*.egg",
    ".eggs",
    "dist",
    "build",
    "docs",
    ".tox",
    ".git",
    "__pycache__",
]
doctest_optionflags = [
    "NUMBER",
    "NORMALIZE_WHITESPACE",
    "IGNORE_EXCEPTION_DETAIL",
]
addopts = [
    "--strict-markers",
    "--tb=short",
    "--doctest-modules",
    "--doctest-continue-on-failure",
]

[tool.coverage.run]
source = [
    "tests",
]

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"

["tool.poetry.group.conda.dependencies"]
appdirs = "^1.4.4"
attrs = "^23.1.0"
Brotli = "^1.1.0"
build = "^0.10.0"
CacheControl = "^0.13.1"
cachy = "^0.3.0"
certifi = "^2023.7.22"
cffi = "^1.16.0"
cfgv = "^3.3.1"
charset-normalizer = "^3.3.1"
cleo = "^2.0.1"
click = "^8.1.7"
click-default-group = "^1.2.4"
clikit = "^0.6.2"
colorama = "^0.4.6"
conda_lock = "^2.4.2"
conda_poetry_liaison = "^0.0.2"
crashtest = "^0.4.1"
cryptography = "^41.0.5"
distlib = "^0.3.7"
dulwich = "^0.21.6"
dunamai = "^1.19.0"
ensureconda = "^1.4.3"
filelock = "^3.13.0"
gitdb = "^4.0.11"
GitPython = "^3.1.40"
html5lib = "^1.1"
identify = "^2.5.31"
idna = "^3.4"
importlib-metadata = "^6.8.0"
importlib-resources = "^6.1.0"
installer = "^0.7.0"
"jaraco.classes" = "^3.3.0"
jeepney = "^0.8.0"
Jinja2 = "^3.1.2"
jsonschema = "^4.17.3"
keyring = "^24.2.0"
MarkupSafe = "^2.1.3"
more-itertools = "^10.1.0"
msgpack = "^1.0.6"
nodeenv = "^1.8.0"
numpy = "^1.26.0"
packaging = "^23.2"
pastel = "^0.2.1"
pexpect = "^4.8.0"
pip = "^23.3.1"
pkginfo = "^1.9.6"
pkgutil_resolve_name = "^1.3.10"
platformdirs = "^3.11.0"
poetry = "^1.6.1"
poetry-core = "^1.7.0"
poetry-dynamic-versioning = "^1.1.1"
poetry-plugin-export = "^1.5.0"
pre-commit = "^3.5.0"
ptyprocess = "^0.7.0"
pycparser = "^2.21"
pydantic = "^2.4.2"
pydantic_core = "^2.10.1"
pylev = "^1.4.0"
pyproject_hooks = "^1.0.0"
pyrsistent = "^0.19.3"
PySocks = "^1.7.1"
PyYAML = "^6.0.1"
rapidfuzz = "^2.15.2"
requests = "^2.31.0"
requests-toolbelt = "^1.0.0"
"ruamel.yaml" = "^0.18.2"
"ruamel.yaml.clib" = "^0.2.7"
SecretStorage = "^3.3.3"
setuptools = "^68.2.2"
shellingham = "^1.5.4"
six = "^1.16.0"
smmap = "^5.0.0"
tomli = "^2.0.1"
tomli_w = "^1.0.0"
tomlkit = "^0.12.1"
toolz = "^0.12.0"
trove-classifiers = "^2023.10.18"
typing_extensions = "^4.8.0"
ukkonen = "^1.0.1"
urllib3 = "^1.26.18"
virtualenv = "^20.24.6"
webencodings = "^0.5.1"
wheel = "^0.41.2"
zipp = "^3.17.0"

[coverage.paths]
source = "reptar"

[coverage.run]
branch = true
omit = [
    "*/__init__.py",
    "*/_version.py",
]

[coverage.report]
fail_under = 50
show_missing = true
